/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "carrier_constants.h"

namespace TCarrier {

const carrierConstants g_carrier_constants;

carrierConstants::carrierConstants() {
}

} // namespace

