/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef carrier_CONSTANTS_H
#define carrier_CONSTANTS_H

#include "carrier_types.h"

namespace TCarrier {

class carrierConstants {
 public:
  carrierConstants();

};

extern const carrierConstants g_carrier_constants;

} // namespace

#endif
